#pragma once
#include <stdio.h>

const char htmlExample[] =
"<!DOCTYPE html> "
"<html lang=\"en\"> "
"<head> " 
"    <meta charset=\"UTF-8\">  " 
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> "
"    <title>historyAPI Example</title>  " 
"    <script language=\"JavaScript\">  " 


"        window.onload = load;  "
"        let lastRequestDir = \"STOP\";  " 

"        function load() {  "
"            console.log(\"ONLOAD\"); "

"            document.addEventListener(\"keydown\", function onPress(event) {  " 
"                var key = event.keyCode;  " 
//"                console.log(key);  "            
"                switch (event.which || event.keyCode) {  " 
"                case 37:  " 
"                    move(\"LEFT\");  " 
"                    break;  " 
"                case 38:  " 
"                    move(\"UP\");  " 
"                    break;  " 
"                case 39:  " 
"                    move(\"RIGHT\");  " 
"                    break;  " 
"                case 40:  " 
"                    move(\"DOWN\");  " 
"                    break;  " 
"                }  " 
"            });  " 

"            document.addEventListener(\"keyup\", function onRelease() { "
//"                 console.log(\"STOP\");    "
"                lastRequestDir = \"STOP\"; "
"                fetch(`http://my-esp32.local/stop`);  " 
"            });    "
"        };  " 

"        function move(direction) {  " 
        
"           if (direction != lastRequestDir) {  "
"               lastRequestDir = direction;  "
"       console.log(direction); "
"               switch (direction) {  " 
"               case \"UP\":  " 
"                 fetch(`http://my-esp32.local/forward`);  " 
"                 break;  "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
"               case \"DOWN\":  " 
"                 fetch(`http://my-esp32.local/backward`);  " 
"                 break;  " 
"               case \"LEFT\":  " 
"                 fetch(`http://my-esp32.local/left`);  " 
"                 break;  " 
"               case \"RIGHT\":  " 
"                 fetch(`http://my-esp32.local/right`);  " 
"                 break;  " 
"               }  "     
"           }  "
"        };  " 

"       function stop() {   "
//"            console.log(\"STOP\");    "
"                lastRequestDir = \"STOP\"; "
"            fetch(`http://my-esp32.local/stop`);  " 
"       }; "
"    </script>  "
"</head>  " 
"<body>  " 
/*
"    <button onclick='move(\"UP\")'>UP</button>  " 
"    <button onclick='move(\"DOWN\")'>DOWN</button>  " 
"    <button onclick='move(\"LEFT\")'>LEFT</button>  " 
"    <button onclick='move(\"RIGHT\")'>RIGHT</button>  " 
*/
"   <button onmousedown='move(\"UP\")' onmouseup='stop()'>UP</button>  " 
"   <button onmousedown='move(\"DOWN\")' onmouseup='stop()'>DOWN</button>  " 
"   <button onmousedown='move(\"LEFT\")' onmouseup='stop()'>LEFT</button>  " 
"   <button onmousedown='move(\"RIGHT\")' onmouseup='stop()'>RIGHT</button>  " 
"</body>  " 
"</html> ";